channels:
- conda-forge
dependencies:
- python=3.9.18
- pip<=23.3.1
- pip:
  - mlflow==2.10.2
  - cloudpickle==3.0.0
  - importlib-metadata==7.0.1
  - numpy==1.26.4
  - packaging==23.1
  - psutil==5.9.0
  - pyyaml==6.0.1
  - scikit-learn==1.3.0
  - scipy==1.11.4
name: mlflow-env
