channels:
- conda-forge
dependencies:
- python=3.9.20
- pip<=24.2
- pip:
  - mlflow==2.10.2
  - cloudpickle==3.1.0
  - numpy==1.26.4
  - packaging==23.2
  - psutil==6.1.0
  - pyyaml==6.0.2
  - scikit-learn==1.3.0
  - scipy==1.13.1
name: mlflow-env
